# Multistage-Dockerfile for application using Alpine 
# Stage 1: Build stage

FROM golang:1.25-alpine AS builder
ARG SERVICE
WORKDIR /app
COPY ${SERVICE}/go.mod ./
COPY ${SERVICE}/go.sum* ./
RUN go mod download
COPY ${SERVICE}/ .
RUN CGO_ENABLED=0 go build -o server ./cmd/main.go

# Stage 2: Final stage

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 8080
ENTRYPOINT [ "./server" ]