apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://grafana-community.github.io/helm-charts
    targetRevision: 6.56.1
    chart: loki
    helm:
      values: |
        loki:
          deploymentMode: SingleBinary
          storage:
            type: filesystem
          schemaConfig:
            configs:
            - from: "2026-03-17"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: standard
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
