apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    targetRevision: 2.6.2
    chart: tempo-distributed
    helm:
      values: |
        tempo:
          minio:
            enabled: false
          storage:
            trace:
              backend: local
              wal:
                backend: local
          compactor:
            enabled: false
        gateway:
          enabled: true
        distributor:
          replicas: 1
        ingester:
          replicas: 2
          persistence:
            enabled: true
            size: 5Gi
        querier:
          replicas: 1
        queryFrontend:
          enabled: false
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
