apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      targetRevision: 6.56.1
      chart: loki
      helm:
        valueFiles:
          - $values/k8s/argo-lgtm-apps/values/loki-values.yaml
    - repoURL: https://github.com/simonkotz/dhbw-devops
      targetRevision: main
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true