apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.5.15
    chart: grafana
    helm:
      values: |
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local:80
                access: proxy
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki-gateway.monitoring.svc.cluster.local:80
                access: proxy
              - name: Tempo
                type: tempo
                url: http://tempo-gateway.monitoring.svc.cluster.local:80
                access: proxy
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
