apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.5.15
    chart: grafana
    helm:
      values: ''
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
