# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Define a matrix of services to build and test in parallel
    strategy:
      matrix:
        service: [auth-service, checkout-service, product-service]
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.7'

    - name: Build ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: go build -v ./...

    - name: Test ${{ matrix.service }}
      working-directory: ./${{ matrix.service }}
      run: go test -v ./...
